### ISSUE TITLE
Markdown formatting controls

### ISSUE THREAD

**Issue by selfagency** [SnowdogApps/wombat#9]
Would it be possible to add some Markdown formatting controls to the Wombat config file? I noticed, for example, that it's adding `id` attributes to my `h1` tags, which I would prefer not to happen.

Thanks

**Comment by Igloczek** [comment]
Could you share some example input and output pair? I didn't saw any weird behavior with Markdown compiler, headings work perfectly fine.

I don't have time to play with this config option now, but will be more than happy to merge a pull request with such feature.

**Comment by selfagency** [comment]
input:
```md
# About
```

output:
```html
<h1 id="about">About</h1>
```

**Comment by Igloczek** [comment]
Ah, it's the default behavior, it just makes every H1 an anchor.

**Comment by vi-cat** [comment]
I've started a merge request that will add the ability to override the default options for the Markdown parser this package uses: https://github.com/showdownjs/showdown

**Comment by selfagency** [comment]
closing this because it's 3 years old and i want to clean up my issues tab
